name: CI - fats

on: {}
  # TODO figure out when and where to run fats tests
  # push:
  #   branches:
  #   - '**'
  #   - '!dependabot/**'

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  GCLOUD_CLIENT_SECRET: ${{ secrets.GCLOUD_CLIENT_SECRET }}
  PIVNET_REFRESH_TOKEN: ${{ secrets.PIVNET_REFRESH_TOKEN }}
  TOOLSMITH_ENV: ${{ secrets.PKS_16_GCP_ENV }}

jobs:

  fats:
    name: FATS
    strategy:
      matrix:
        config:
        - os: ubuntu-latest
          qualifier: kind
          cluster: kind
          registry: docker-daemon
        - os: ubuntu-latest
          qualifier: dockerhub
          cluster: kind
          registry: dockerhub
        - os: ubuntu-latest
          qualifier: gke
          cluster: gke
          registry: gcr
        - os: ubuntu-latest
          qualifier: pks
          cluster: pks-gcp
          registry: gcr
        - os: windows-latest
          qualifier: windows
          cluster: gke
          registry: gcr
      fail-fast: false
    runs-on: ${{ matrix.config.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup env
      run: |
        job=$(date +%s) # TODO use something that is assigned by CI to guarantee uniqueness
        echo "JOB_ID=${job}"

        echo "##[set-env name=CLUSTER]${{ matrix.config.cluster }}"
        echo "##[set-env name=REGISTRY]${{ matrix.config.registry }}"
        echo "##[set-env name=CLUSTER_NAME]fats-${job}-${{ matrix.config.qualifier }}"
        echo "##[set-env name=NAMESPACE]fats-${job}-${{ matrix.config.qualifier }}"
      shell: bash
    - name: Start FATS
      run: ./fats/start.sh
      shell: bash
      timeout-minutes: 45
    - name: Install riff
      run: .github/workflows/ci-fats/install.sh
      shell: bash
      timeout-minutes: 10
    - name: Run Tests
      run: .github/workflows/ci-fats/run.sh
      shell: bash
      timeout-minutes: 30
    - name: Collect diagnostics
      run: ./fats/diagnostics.sh
      shell: bash
      if: always()
      timeout-minutes: 1
    - name: Cleanup riff
      run: .github/workflows/ci-fats/cleanup.sh
      shell: bash
      if: always()
      timeout-minutes: 20
    - name: Cleanup FATS
      run: ./fats/cleanup.sh
      shell: bash
      if: always()
      timeout-minutes: 30
