name: CI - kafka-provisioner

on:
  push:
    branches:
    - '**'
    - '!dependabot/**'
  pull_request: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Golang
      uses: actions/setup-go@v1
      with:
        go-version: '1.13'
    # TODO remove after https://github.com/actions/setup-go/issues/14
    - name: Add GOPATH/bin to PATH
      run: |
        echo "##[set-env name=GOPATH;]$(go env GOPATH)"
        echo "##[add-path]$(go env GOPATH)/bin"
      working-directory: kafka-provisioner
      shell: bash
    - name: Install ko
      run: GO111MODULE=on go get github.com/google/ko/cmd/ko
      working-directory: kafka-provisioner
      shell: bash
    - name: Check out code
      uses: actions/checkout@v2
    - name: Run tests
      run: make build test
      working-directory: kafka-provisioner
      shell: bash
    - name: Build using ko
      run: ko publish -L github.com/projectriff/riff/developer-utils/cmd/provisioner
      working-directory: kafka-provisioner
      shell: bash
    - name: Publish
      if: |
        github.event_name == 'push' && startsWith(github.repository, 'projectriff/') && (
          github.ref == 'refs/heads/master' || (
            startsWith(github.ref, 'refs/heads/v') && endsWith(github.ref, 'x')
          )
        )
      run: ../.github/workflows/ci-kafka-provider/publish.sh
      working-directory: kafka-provisioner
      shell: bash
      env:
        GCLOUD_CLIENT_SECRET: ${{ secrets.GCLOUD_CLIENT_SECRET }}
